#!/bin/bash

# Root directory name
ROOT_DIR=~/linux_training/bbb-project

# Define folder names and their descriptions
declare -A folders=(
  ["01_documents"]="Personal notes, weekly planning, and explanations you write."
  ["02_resources"]="Read-only resources: PDFs, datasheets, books, articles, and reference code."
  ["03_slides"]="Slides or presentations you create during your learning journey."
  ["04_examples"]="Clean and working drivers, user apps, and final sample code."
  ["05_practice"]="Practice and experimental code — sandbox space for trying ideas."
  ["06_scripts"]="Reusable scripts for build, deployment, overlay compilation, etc."
  ["07_overlays"]="Device Tree source (.dts) and compiled (.dtbo) files."
  ["08_kernel"]="Kernel source setup, patch notes, and configuration-related materials."
  ["09_uBoot"]="uBoot source setup, patch notes, and configuration-related materials."
  ["10_rootfs"]="rootfs, This folder contains setup notes, patches, and configurations related to the BeagleBone Black Debian root filesystem used for testing and development."
  ["11_logs"]="Collected dmesg, SPI logs, boot logs, etc., for debugging."
  ["12_tests"]="Test scripts or automation to validate your drivers and apps."
)

# Create root directory
mkdir -p "$ROOT_DIR"

# Create each folder with a README
for dir in "${!folders[@]}"; do
  mkdir -p "$ROOT_DIR/$dir"
  cat > "$ROOT_DIR/$dir/README.md" <<EOF
# $dir

${folders[$dir]}

> Auto-generated by \`create_bbb_project.sh\`
EOF
done

# Create top-level README.md
cat > "$ROOT_DIR/README.md" <<EOF
# BeagleBone Black SPI Driver Project

This project is a structured, 12-week exploration of Linux device driver development, focusing on the SPI subsystem on the BeagleBone Black. It includes:

- Environment setup
- Kernel module programming
- SPI userspace & kernel driver development
- Device Tree overlay usage
- Yocto integration and automation

Each directory represents a key area in your training pipeline. Explore each folder’s README for details.

## Structure

| Folder        | Purpose |
|---------------|---------|
$(for dir in "${!folders[@]}"; do printf "| %-13s | %s |\n" "$dir" "${folders[$dir]}"; done)

---

> Created on: $(date)
EOF

echo "✅ Directory structure created in: $ROOT_DIR"
